#' Generate basic files to get an RC package to run
#'
#' @param package.name character Name of package
#' @param dir character Folder where package is being created
#' @param author.name character Your name, to place in DESCRIPTION
#' @param author.email character Your email, to place in DESCRIPTION
#'
#' @export make.skeleton
#'
make.skeleton <- function(dir, package.name, short.name, 
                          author.name = NULL, author.email = NULL) {
  if (missing(dir)) {
    stop('You must provide the folder where you are building the package')
  }
  if (missing(package.name)) stop('You must provide the package name')
  if (missing(short.name)) short.name <- package.name
  if (!dir.exists(paste0(dir, 'R'))) {
    dir.create((paste0(dir, 'R')))
  }
  
  make.description(package.name, dir, author.name, author.email)
  make.namespace(dir)
  make.conf(package.name, short.name, dir)
  make.daemon(package.name, short.name, dir)
  make.parameters(package.name, short.name, dir)
  make.strategy(package.name, short.name, dir)
  make.plotter(package.name, short.name, dir)
  print("Done!")
}

make.description <- function(package.name, dir, author.name, author.email) {
  if (file.exists(paste0(dir, "DESCRIPTION"))) {
    warning('DESCRIPTION exists; file not overwritten.')
    return()
  }
  nm <- strsplit(author.name, " ")[[1]]
  sink(paste0(dir, "DESCRIPTION"))
  cat(paste0("Package: ", package.name, "\n"))
  cat("Title: ---\n")
  cat("Version: 0.0.1\n")
  cat(paste0("Date: ", Sys.Date(), "\n"))
  cat("Description: ---\n")
  cat("License: ---\n")
  cat("LazyData: true\n")
  cat(paste0("Authors@R: person(given = '", nm[1], "', family = '", nm[2],
             "', role = c('aut', 'cre'), email = '", author.email, "')\n"))
  cat(paste0("RoxygenNote: ", packageVersion('roxygen2'), "\n"))
  cat("Imports:\n")
  cat("  rcvirtual\n")
  cat("Suggests:\n")
  cat("  testthat\n")
  sink()
}

make.namespace <- function(dir) {
  if (file.exists(paste0(dir, "NAMESPACE"))) {
    warning('NAMESPACE exists; file not overwritten.')
    return()
  }
  sink(paste0(dir, "NAMESPACE"))
  cat("# Generated by roxygen2: do not edit by hand; use devtools::document() instead")
  sink()
}

make.conf <- function(package.name, short.name, dir) {
  fn <- paste0(dir, "R/", short.name, "-conf.R")
  if (file.exists(fn)) {
    warning('conf exists; file not overwritten.')
    return()
  }
  sink(fn)
  cat("#' Template configuration for this package\n")
  cat("#'\n")
  cat("#' @import rcvirtual\n")
  cat("#' @export rcage.conf\n")
  cat("#' @exportClass rcage.conf\n")
  cat("#'\n")
  cat(paste0(package.name, ".conf <- setRefClass(\n"))
  cat(paste0("  Class = '", package.name, ".conf',\n"))
  cat("  contains = 'rcvirtual.conf',\n")
  cat("  methods = list(\n")
  cat("    construct = function(){\n")
  cat("\n")      
  cat("      callSuper()\n")
  cat("\n")      
  cat(paste0("      .self$package.name <- ", package.name, "\n"))
  cat("      t.posix <- as.POSIXlt(c('1964/01/01', '2004/01/01'), tz = 'GMT')\n")
  cat("      t.bnd <- as.numeric(t.posix)\n")
  cat("\n")      
  cat("      #-------------------------------------------------------------------------\n")
  cat("      # Daemon conf\n")
  cat("      #-------------------------------------------------------------------------\n")
  cat("      .self$daemon <- list(timeb = t.bnd)\n")
  cat("\n")      
  cat("      #-------------------------------------------------------------------------\n")
  cat("      # Strategy conf\n")
  cat("      #-------------------------------------------------------------------------\n")
  cat("      .self$strategy <- list(timeb = t.bnd)\n")
  cat("\n")        
  cat("      #-------------------------------------------------------------------------\n")
  cat("      # Plotter conf\n")
  cat("      #-------------------------------------------------------------------------\n")
  cat("      .self$plotter <- list(timeb = t.bnd)\n")
  cat("\n")      
  cat("      #-------------------------------------------------------------------------\n")
  cat("      # Parameter conf\n")
  cat("      #-------------------------------------------------------------------------\n")
  cat("      df <- .self$get.conf.template()\n")
  cat("      sk <- function(name) {\n")
  cat("        as.numeric(mapply(name, FUN = function(name) which(df$name == name)))\n")
  cat("      }\n")
  cat("      df$type[sk(c('Y', 't'))] <- 'fixed'\n")
  cat("      df$type[sk('K')] <- 'derived'\n")
  cat("      df$type[sk('phi')] <- 'unknown'\n")
  cat("      df$type[sk('theta')] <- 'processes'\n")
  cat("      df$type[sk('chi')] <- 'conjugate normal parameter'\n")
  cat("\n")      
  cat("      df$initial[sk('phi')] <- 0.1\n")
  cat("\n")      
  cat("      df$lbound[sk('phi')] <- 0\n")
  cat("\n")      
  cat("      df$ubound[sk('phi')] <- 1\n")
  cat("\n")      
  cat("      df$long.name[sk('Y')] <- 'catches'\n")
  cat("      df$long.name[sk('t')] <- 'time'\n")
  cat("      df$long.name[sk('K')] <- 'carrying capacity'\n")
  cat("      df$long.name[sk('phi')] <- 'elasticity'\n")
  cat("      df$long.name[sk('theta')] <- 'log-abundance at age'\n")
  cat("      df$long.name[sk('chi')] <- 'log-catchability'\n")
  cat("\n")      
  cat("      df$is.spatial.avg[sk('Y')] <- TRUE\n")
  cat("\n")      
  cat("      df$store.in.ram[sk('Y')] <- TRUE\n")
  cat("\n")      
  cat("      df$units[sk('t')] <- 'year'\n")
  cat("\n")      
  cat("      out.dir <- paste0(tempdir(), '/')\n")
  cat("      df$output.file[sk('Y')] <- paste0(out.dir, 'observations.csv')\n")
  cat("\n")      
  cat("      .self$parameters <- df[df$type != '-', ]\n")
  cat("    }\n")
  cat("  )\n")
  cat(")\n")
  sink()
}

make.daemon <- function(package.name, short.name, dir) {
  fn <- paste0(dir, "R/", short.name, "-conf.R")
  if (file.exists(fn)) {
    warning('conf exists; file not overwritten.')
    return()
  }
  sink(fn)
  
  sink(paste0(dir, short.name, "-daemon.R"))
  cat(paste0("#' ", package.name, ": daemon for this package\n"))
  cat("#'\n") 
  cat("#' @import rcvirtual\n")
  car(paste0("#' @export ", package.name, "\n"))
  cat(paste0("#' @exportClass ", package.name, "\n"))
  cat("#'\n")
  cat(paste0(package.name, " <- setRefClass(\n"))
  cat(paste0("  Class = '", package.name, "',\n"))
  cat("  contains = c('rcvirtual.daemon'),\n")
  cat("  methods = list(\n")
  cat("    initialize = function(uconf = NULL, verbose = TRUE, autoconstruct = TRUE){\n")
  cat("      'Initialize a daemon object'\n")
  cat("\n")
  cat(paste0("      p.name <- '", package.name, "'\n"))
  cat("      if (is.null(uconf)) {\n")
  cat("        uconf <- rcage.conf$new(package.name = p.name, \n")
  cat("                                object.name = paste0(p.name, '.conf'))\n")
  cat("        uconf$construct()\n")
  cat("      }\n")        
  cat("\n")      
  cat("      callSuper(package.name = p.name,\n")
  cat("                object.name = '.daemon',\n")
  cat("                conf = uconf)\n")
  cat("    }\n")
  cat("  )")
  cat(")\n")
  sink()
}

make.template <- function(package.name, short.name, dir, obj.name) {
  fn <- paste0(dir, "R/", short.name, "-", obj.name, ".R")
  sink(fn)
  cat(paste0("#' ", obj.name, " class\n"))
  cat("#'\n")
  cat("#' @import rcvirtual\n")
  cat(paste0("#' @export ", package.name, ".", obj.name, "\n"))
  cat(paste0("#' @exportClass ", package.name, ".", obj.name, "\n"))
  cat("#'\n")
  cat(paste0(package.name, ".", obj.name, " <- setRefClass(\n"))
  cat(paste0("  Class = '", package.name, ".", obj.name, "',\n"))
  cat(paste0("  contains = 'rcvirtual.", obj.name, "'\n"))
  cat(")\n")
  sink()
}

make.parameters <- function(package.name, short.name, dir) {
  make.template(package.name, short.name, dir, "parameters")
}

make.strategy <- function(package.name, short.name, dir) {
  make.template(package.name, short.name, dir, "strategy")
}

make.plotter <- function(package.name, short.name, dir) {
  make.template(package.name, short.name, dir, "plotter")
}